#!/bin/sh
if [ -z "$1" ]; then
    cfg="$(basename $0 | sed 's/run_sim_hessarray_\(.*\)$/\1/' | sed 's/run_sim_telarray_\(.*\)$/\1/' | sed 's/run_sim_\(.*\)$/\1/')"
    name=$(echo $0 | grep hess 2>&1 >/dev/null && echo sim_hessarray || echo sim_telarray)
    echo "Starting run_${name}_generic script for configuration '${cfg}'."
else
    cfg="$1"
    shift
    name=$(basename $0 )
    echo "Starting run_${name}_generic script for configuration '${cfg}'."
fi

if [ -z "${SIM_TELARRAY_PATH}" ]; then
   SIM_TELARRAY_RUN_PATH="$(cd $(dirname $0) && pwd -P)"
   if [ "${SIM_TELARRAY_RUN_PATH}" = "." ]; then
      SIM_TELARRAY_RUN_PATH="$(pwd -P)"
   fi
   if [ "$(dirname ${SIM_TELARRAY_RUN_PATH})" = "sim_telarray" ]; then
      SIM_TELARRAY_PATH="$(dirname ${SIM_TELARRAY_RUN_PATH})"
   else
      SIM_TELARRAY_PATH="${SIM_TELARRAY_RUN_PATH}"
   fi
fi

export SIM_TELARRAY_PATH
export cfg

cd ${SIM_TELARRAY_PATH} || exit 1

echo "Working directory is `/bin/pwd`"

printenv | grep CORSIKA

multicfg=""

if [ -f "${SVNPROD2}/CODE/multi_${cfg}.cfg" ]; then
   multicfg="${SVNPROD2}/CODE/multi_${cfg}.cfg"
fi

if [ "${multicfg}" = "" ]; then
   echo "Cannot locate configuration file multi_${cfg}.cfg"
   exit 1
else
    echo "multipipe configuration file is ${multicfg}"
fi

set -x

bin/multipipe_corsika -c "${multicfg}" || echo 'Fan-out failed'
